apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-service
  name: nginx-service
spec:
  ports:
  - name: http
    nodePort: 30081
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: NodePort
